let suggestions = [
    "grapdroad",
    "youtube",
    "facebook",
    "designer",
    "developer",
    "web designer",
    "login form using html,css",
    "learn coding",
    "facebook login",
    "facebook signup",
    "html,css,js course",
    "how to create youtube channel",
    "html",
    "Css",
    "js",
    "coding",
    "how to create website",
]